# Generated by Django 4.0.6 on 2022-08-09 15:50

from typing import Tuple

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[Tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="PredictionConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Saliency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rdwatch.predictionconfiguration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SatelliteImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor",
                    models.CharField(
                        choices=[("L8", "Landsat 8"), ("S2", "Sentinel 2")],
                        max_length=2,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="TrackingConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("threshold", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("AC", "Active Construction"),
                            ("SP", "Site Preperation"),
                        ],
                        max_length=2,
                    ),
                ),
                ("score", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rdwatch.trackingconfiguration",
                    ),
                ),
                (
                    "saliency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rdwatch.saliency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaliencyTile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raster", django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                (
                    "saliency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rdwatch.saliency",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="saliency",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="rdwatch.satelliteimage"
            ),
        ),
    ]
