# Generated by Django 4.1 on 2022-09-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rdwatch", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SatelliteImage",
        ),
    ]
