# Generated by Django 4.1.5 on 2023-02-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdwatch", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteevaluation",
            name="status",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
