# Generated by Django 4.1 on 2022-08-22 06:42

import django.contrib.postgres.constraints
import rdwatch.db.functions
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rdwatch", "0002_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="saliencytile",
            name="exclude_overlapping_raster",
        ),
        migrations.AddConstraint(
            model_name="saliencytile",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (rdwatch.db.functions.RasterXRange("raster"), "&&"),
                    (rdwatch.db.functions.RasterYRange("raster"), "&&"),
                    ("saliency", "="),
                ],
                name="exclude_overlapping_raster",
                violation_error_message=(  # type: ignore
                    "Tiles for the same raster cannot overlap"
                ),
            ),
        ),
    ]
