# Generated by Django 4.1 on 2022-08-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdwatch", "0003_saliencytile_range_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="label",
            field=models.CharField(
                choices=[
                    ("AC", "Active Construction"),
                    ("SP", "Site Preperation"),
                    ("PC", "Post Construction"),
                ],
                help_text="Site classification label",
                max_length=2,
            ),
        ),
    ]
