# Generated by Django 4.1 on 2022-11-23 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdwatch", "0003_delete_satelliteimage"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="siteobservation",
            name="uniq_siteobv",
        ),
        migrations.AlterField(
            model_name="region",
            name="number",
            field=models.PositiveSmallIntegerField(
                db_index=True, help_text="The region number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="siteobservation",
            name="constellation",
            field=models.ForeignKey(
                help_text="The source image's satellite constellation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="rdwatch.constellation",
            ),
        ),
        migrations.AlterField(
            model_name="siteobservation",
            name="spectrum",
            field=models.ForeignKey(
                help_text="The source image's satellite spectrum",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="rdwatch.commonband",
            ),
        ),
    ]
