# Generated by Django 4.1.5 on 2023-04-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rdwatch', '0005_alter_siteobservation_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteobservation',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
