# Generated by Django 4.1.9 on 2023-05-10 08:47

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdwatch', '0006_alter_siteobservation_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='percent_black',
            field=models.FloatField(help_text='NoData coverage on image', null=True),
        ),
        migrations.CreateModel(
            name='Retrieving',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('timestamp', models.DateTimeField(help_text='Start time of the task')),
                (
                    'status',
                    models.TextField(
                        blank=True, help_text='Complete, Retrieving, Error'
                    ),
                ),
                (
                    'error',
                    models.TextField(
                        blank=True, help_text='Error text if an error occurs'
                    ),
                ),
                (
                    'siteeval',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='rdwatch.siteevaluation',
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='retrieving',
            index=django.contrib.postgres.indexes.GistIndex(
                fields=['timestamp'], name='rdwatch_ret_timesta_48d0b8_gist'
            ),
        ),
    ]
