# Generated by Django 4.1.9 on 2023-05-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rdwatch', '0006_alter_siteobservation_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='percent_black',
            field=models.FloatField(help_text='NoData coverage on image', null=True),
        ),
        migrations.CreateModel(
            name='SatelliteFetching',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('timestamp', models.DateTimeField(help_text='Start time of the task')),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('Complete', 'Complete'),
                            ('Running', 'Running'),
                            ('Error', 'Error'),
                        ],
                        help_text='Fetching Status',
                        max_length=255,
                    ),
                ),
                (
                    'error',
                    models.TextField(
                        blank=True, help_text='Error text if an error occurs'
                    ),
                ),
                (
                    'siteeval',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='rdwatch.siteevaluation',
                    ),
                ),
            ],
        ),
    ]
