# Generated by Django 4.1.9 on 2023-05-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rdwatch', '0007_siteimage_percent_black_satellitefetching'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitefetching',
            name='celery_id',
            field=models.CharField(
                blank=True, help_text='Celery Task Id', max_length=255
            ),
        ),
    ]
