# Generated by Django 4.1.9 on 2023-07-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rdwatch', '0011_siteimage_aws_location_siteimage_image_bbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteobservation',
            name='timestamp',
            field=models.DateTimeField(
                help_text="The source image's timestamp", null=True
            ),
        ),
    ]
