# Generated by Django 4.1.9 on 2023-07-13 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rdwatch', '0011_siteimage_aws_location_siteimage_image_bbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitefetching',
            name='configuration',
            field=models.ForeignKey(
                blank=True,
                help_text='The hyper parameters used this site evaluation.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='rdwatch.hyperparameters',
            ),
        ),
    ]
