# Generated by Django 4.1.9 on 2024-01-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rdwatch', '0022_rename_siteeval_satellitefetching_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteevaluation',
            name='modified_timestamp',
            field=models.DateTimeField(
                auto_now=True, help_text='Timestamp of the last modification'
            ),
        ),
    ]
