# Generated by Django 5.0.3 on 2024-04-11 18:06
from __future__ import annotations

from typing import TYPE_CHECKING

import django.db.models.deletion
from django.db import migrations, models

if TYPE_CHECKING:
    from django.contrib.gis.db.backends.postgis.schema import PostGISSchemaEditor
    from django.db.migrations.state import StateApps


def migrate_regions(apps: StateApps, schema_editor: PostGISSchemaEditor):
    ModelRun = apps.get_model('rdwatch', 'ModelRun')
    SiteEvaluation = apps.get_model('rdwatch', 'SiteEvaluation')  # noqa: N806

    # Clean up any empty model runs, as they will not have an associated region
    ModelRun.objects.alias(site_count=models.Count('evaluations')).filter(
        site_count=0
    ).delete()

    # Set the region for each model run to the region of the first site evaluation
    # (which should be the same for all sites in a model run)
    ModelRun.objects.update(
        region=SiteEvaluation.objects.filter(
            configuration=models.OuterRef('pk'),
        ).values('region')[:1]
    )


class Migration(migrations.Migration):
    dependencies = [
        ('rdwatch', '0025_siteimage_image_embedding'),
    ]

    operations = [
        # Add the `region` as a column on `ModelRun`, allowing it to
        # be nullable initially
        migrations.AddField(
            model_name='modelrun',
            name='region',
            field=models.ForeignKey(
                help_text='The region this model run belongs to',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='rdwatch.region',
                related_name='model_runs',
            ),
        ),
        # Migrate the regions from `SiteEvaluation` to `ModelRun`
        migrations.RunPython(code=migrate_regions),
        # Now that all model runs have a region, make the column non-nullable
        migrations.AlterField(
            model_name='modelrun',
            name='region',
            field=models.ForeignKey(
                help_text='The region this model run belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='model_runs',
                to='rdwatch.region',
            ),
        ),
    ]
