# Generated by Django 5.0.3 on 2024-04-12 09:56

# Generated by Django 5.0.3 on 2024-04-11 18:06
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rdwatch', '0026_remove_siteevaluation_region_modelrun_region'),
    ]

    operations = [
        # Remove the `region` column from `SiteEvaluation` now that it
        # has been migrated to `ModelRun`
        migrations.RemoveField(
            model_name='siteevaluation',
            name='region',
        ),
    ]
