# Generated by Django 3.2.9 on 2021-11-17 04:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211117_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='stacfile',
            name='outline',
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
