# Generated by Django 3.2.9 on 2021-11-15 23:13

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import rgd.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_imagery', '0007_auto_20210927_1501'),
        ('rgd', '0005_auto_20211105_1715'),
        ('core', '0003_auto_20211104_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='STACFile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('failure_reason', models.TextField(null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('created', 'Created but not queued'),
                            ('queued', 'Queued for processing'),
                            ('running', 'Processing'),
                            ('failed', 'Failed'),
                            ('success', 'Succeeded'),
                            ('skipped', 'Skipped'),
                        ],
                        default='created',
                        max_length=20,
                    ),
                ),
                ('server_modified', models.DateTimeField(blank=True, default=None, null=True)),
                ('processed', models.DateTimeField(blank=True, default=None, null=True)),
                (
                    'checksumfile',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='rgd.checksumfile',
                    ),
                ),
                (
                    'raster',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='rgd_imagery.raster',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(models.Model, rgd.models.mixins.PermissionPathMixin),
        ),
        migrations.DeleteModel(
            name='STACItem',
        ),
    ]
