# Generated by Django 3.2.10 on 2021-12-10 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rgd', '0005_auto_20211105_1715'),
        ('core', '0004_stacfile_outline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stacfile',
            name='file',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='rgd.checksumfile',
                unique=True,
            ),
        ),
    ]
