# Generated by Django 3.2.11 on 2022-01-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_stacfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='region',
            name='status',
        ),
        migrations.AlterField(
            model_name='feature',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
