# Generated by Django 3.2.11 on 2022-01-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgd', '0007_auto_20211215_0608'),
        ('core', '0006_auto_20220124_0548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='Site',
        ),
    ]
