# Generated by Django 3.2.11 on 2022-02-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_observation_region_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.CharField(max_length=1000),
        ),
    ]
