# Generated by Django 3.2.11 on 2022-01-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_observation_region_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
