#  To get better performance during local demos
version: '3'
services:
  django:
    command: ["gunicorn", "-k", "gthread", "--threads", "8", "--bind", "0.0.0.0:8000", "watch.wsgi"]
    environment:
      - DJANGO_CONFIGURATION=NonDebugDevConfiguration
