# Generated by Django 4.1.9 on 2024-03-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rdwatch_scoring', '0002_satellitefetching_siteimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='image_embedding',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
