# Generated by Django 5.0.9 on 2024-10-16 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scoring', '0007_siteimage_migrate_data_aws_uri_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteimage',
            name='aws_location',
        ),
    ]
