# Generated by Django 4.1.9 on 2023-10-30 22:04

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rdwatch_scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteFetching',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('timestamp', models.DateTimeField(help_text='Start time of the task')),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('Complete', 'Complete'),
                            ('Running', 'Running'),
                            ('Error', 'Error'),
                        ],
                        help_text='Fetching Status',
                        max_length=255,
                    ),
                ),
                (
                    'celery_id',
                    models.CharField(
                        blank=True, help_text='Celery Task Id', max_length=255
                    ),
                ),
                (
                    'error',
                    models.TextField(
                        blank=True, help_text='Error text if an error occurs'
                    ),
                ),
                ('site', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'timestamp',
                    models.DateTimeField(help_text="The source image's timestamp"),
                ),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                (
                    'cloudcover',
                    models.FloatField(
                        help_text='Cloud Cover associated with Image', null=True
                    ),
                ),
                (
                    'percent_black',
                    models.FloatField(help_text='NoData coverage on image', null=True),
                ),
                (
                    'source',
                    models.CharField(
                        blank=True, help_text='WV, S2, L8 imagery source', max_length=2
                    ),
                ),
                (
                    'image_bbox',
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, help_text='Image Bounding Box', null=True, srid=4326
                    ),
                ),
                (
                    'image_dimensions',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), null=True, size=2
                    ),
                ),
                (
                    'aws_location',
                    models.CharField(
                        blank=True,
                        help_text='S3 Link to base file used to download this image',
                        max_length=2048,
                    ),
                ),
                ('site', models.CharField(max_length=255)),
                ('observation', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='siteimage',
            index=django.contrib.postgres.indexes.GistIndex(
                fields=['timestamp'], name='rdwatch_sco_timesta_17ef97_gist'
            ),
        ),
    ]
