# Generated by Django 4.1.9 on 2023-11-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rdwatch_scoring', '0002_satellitefetching_siteimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitefetching',
            name='model_run_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
