---
- hosts: all
  vars:
    app_path: /home/ubuntu/ResonantGeoData
  tasks:
  - name: checkout code
    git:
      repo: "https://github.com/ResonantGeoData/ResonantGeoData.git"
      dest: "{{ app_path }}"
      version: production
      force: yes

  - name: install pip
    apt: 
      pkg:
        - python3-pip
      update_cache: yes
      state: present
    become: yes

  - name: pip docker + docker-compose
    pip:
      name: 
        - docker
        - docker-compose
    become: yes

  - name: start docker daemon
    include_role:
      name: geerlingguy.docker
    vars:
      ansible_become: yes
      
  - name: tear down existing services
    community.docker.docker_compose:
      project_src: "{{ app_path }}"
      state: absent
    register: output
    become: yes

  - ansible.builtin.debug:
      var: output

  - name: pull docker images
    community.docker.docker_compose:
      project_src: "{{ app_path }}"
      pull: yes
      files:
        - docker-compose.yml
    register: output
    become: yes


  - ansible.builtin.debug:
      var: output

  - name: build docker images
    community.docker.docker_compose:
      project_src: "{{ app_path }}"
      build: yes
      files:
        - docker-compose.yml
    register: output
    become: yes

  - ansible.builtin.debug:
      var: output

  - name: start docker services
    community.docker.docker_compose:
      project_src: "{{ app_path }}"
      files:
        - docker-compose.yml
    register: output
    become: yes