---
all:
  hosts:
    watch:
      ansible_host: 127.0.0.1
      ansible_user: ubuntu
      ansible_ssh_common_args: -o ProxyCommand='aws ssm start-session --target i-0e3777724198d81d1 --document-name RGD_SSHDocument --parameters "portNumber=%p"'
