# Generated by Django 4.1.5 on 2023-03-20 13:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_region_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                help_text='Polygon from the associated Region Feature',
                null=True,
                srid=3857,
            ),
        ),
        migrations.AddField(
            model_name='region',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                help_text='Polygon from the associated Region Feature',
                null=True,
                srid=3857,
            ),
        ),
    ]
