# Generated by Django 4.1.9 on 2023-09-07 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_hyperparameters_ground_truth_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='siteevaluation',
            name='unique_siteeval',
        ),
    ]
