# Generated by Django 4.1.11 on 2023-10-11 14:59

import django_extensions.db.fields

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_siteobservationtracking_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteevaluation',
            name='timestamp',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
    ]
