# Generated by Django 4.1.9 on 2023-10-26 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rdwatch', '0021_rename_siteobs_siteimage_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satellitefetching',
            old_name='siteeval',
            new_name='site',
        ),
    ]
