# Generated by Django 4.1.9 on 2024-02-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0024_siteevaluationtracking_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='image_embedding',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
