# Generated by Django 5.0.3 on 2024-04-11 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_siteimage_image_embedding'),
    ]

    operations = [
        # Add the `region` as a column on `ModelRun`, allowing it to
        # be nullable initially
        migrations.AddField(
            model_name='modelrun',
            name='region',
            field=models.ForeignKey(
                help_text='The region this model run belongs to',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.region',
                related_name='model_runs',
            ),
        ),
    ]
