# Generated by Django 5.0.3 on 2024-04-25 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0029_satellitefetching_rdwatch_sat_status_753c74_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='slug',
            new_name='short_code',
        ),
        migrations.RenameField(
            model_name='performer',
            old_name='description',
            new_name='team_name',
        ),
    ]
