# Generated by Django 5.0.3 on 2024-07-01 09:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0031_remove_region_uniq_region_modelrun_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteevaluation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Point from this site's Site Feature", null=True, srid=3857
            ),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(
                help_text='Point of site observation', null=True, srid=3857
            ),
        ),
        migrations.AlterField(
            model_name='siteevaluation',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(
                help_text="Polygon from this site's Site Feature", null=True, srid=3857
            ),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(
                help_text='Footprint of site observation', null=True, srid=3857
            ),
        ),
    ]
