# Generated by Django 5.0.3 on 2024-08-02 13:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0031_remove_region_uniq_region_modelrun_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteevaluation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Point from this site's Site Feature", null=True, srid=3857
            ),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(
                help_text='Point of site observation', null=True, srid=3857
            ),
        ),
        migrations.AlterField(
            model_name='siteevaluation',
            name='configuration',
            field=models.ForeignKey(
                help_text='The hyper parameters used this site evaluation.',
                on_delete=django.db.models.deletion.CASCADE,
                to='core.modelrun',
            ),
        ),
        migrations.AlterField(
            model_name='siteevaluation',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(
                help_text="Polygon from this site's Site Feature", null=True, srid=3857
            ),
        ),
        migrations.AlterField(
            model_name='siteobservation',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(
                help_text='Footprint of site observation', null=True, srid=3857
            ),
        ),
        migrations.AddConstraint(
            model_name='siteevaluation',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('geom__isnull', False), ('point__isnull', True)),
                    models.Q(('geom__isnull', True), ('point__isnull', False)),
                    _connector='OR',
                ),
                name='site_geom_or_point_not_null',
                violation_error_message='Exactly one of [geom, point] must be non-null',
            ),
        ),
        migrations.AddConstraint(
            model_name='siteobservation',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('geom__isnull', False), ('point__isnull', True)),
                    models.Q(('geom__isnull', True), ('point__isnull', False)),
                    _connector='OR',
                ),
                name='siteobs_geom_or_point_not_null',
                violation_error_message='Exactly one of [geom, point] must be non-null',
            ),
        ),
    ]
