# Generated by Django 5.0.3 on 2024-07-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0032_siteevaluation_point_siteobservation_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteevaluation',
            name='configuration',
            field=models.ForeignKey(
                help_text='The hyper parameters used this site evaluation.',
                on_delete=django.db.models.deletion.CASCADE,
                to='core.modelrun',
            ),
        ),
    ]
