# Generated by Django 5.0.3 on 2024-08-15 13:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0033_remove_region_unique_region_with_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteevaluationtracking',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Point from this site's Site Feature", null=True, srid=3857
            ),
        ),
    ]
