# Generated by Django 5.0.3 on 2024-09-23 15:13

import uuid

import s3_file_field.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0035_alter_annotationexport_export_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRunUpload',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('title', models.CharField(max_length=1000)),
                (
                    'private',
                    models.BooleanField(
                        default=False,
                        help_text='Whether this model run should be private',
                    ),
                ),
                (
                    'region',
                    models.CharField(
                        blank=True,
                        help_text='Override for the region this model run belongs to',
                        max_length=1000,
                    ),
                ),
                (
                    'performer',
                    models.CharField(
                        blank=True,
                        help_text='Shortcode override for the team that produced this evaluation',
                        max_length=1000,
                    ),
                ),
                ('zipfile', s3_file_field.fields.S3FileField()),
                (
                    'task_id',
                    models.CharField(help_text='Celery task ID', max_length=256),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='animationmodelrunexport',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='core_animationmodelrunexports',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='animationsiteexport',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='core_animationsiteexports',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
