# Generated by Django 5.0.3 on 2024-10-17 08:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


def compute_model_run_aggregate_stats(apps, schema_editor):
    from rdwatch.core.models import ModelRun

    ModelRun.compute_all_aggregate_stats(recompute_all=True)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0037_alter_animationmodelrunexport_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='cached_bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                help_text='The bounding box of all evaluations for this model run',
                null=True,
                spatial_index=False,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='cached_numsites',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='The number of distinct evaluations for this model run',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='cached_score',
            field=models.FloatField(
                blank=True,
                help_text='The average score of all evaluations for this model run',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='cached_timerange_max',
            field=models.DateTimeField(
                blank=True,
                help_text='The latest timestamp of any evaluation for this model run',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='cached_timerange_min',
            field=models.DateTimeField(
                blank=True,
                help_text='The earliest timestamp of any evaluation for this model run',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='cached_timestamp',
            field=models.DateTimeField(
                blank=True,
                help_text='The timestamp of the most recent evaluation for this model run',
                null=True,
            ),
        ),
        migrations.RunPython(
            code=compute_model_run_aggregate_stats,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
