# Generated by Django 5.0.3 on 2024-10-21 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0038_modelrun_cached_bbox_modelrun_cached_numsites_and_more'),
        ('core', '0040_remove_siteimage_aws_location'),
    ]

    operations = []
